# Site settings
title: Professional Portfolio for Adrian Padamadan
description: desc
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adrian Padamadan
user_description: 2nd Year Robotics Engeering Student but I have a lot of experience with a lot of different things. My best skill is how quickly I learn. Check my experience for everything I've worked with.
user_title: Robotics Engineer
email: padamadan.adrian@gmail.com
github_username:  adrpad

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
