# Site settings
title: Adrian Padamadan - Robotics Engineering Portfolio
description: desc
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://www.adrpad.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adrian Padamadan
user_description: I am a 2nd Year Robotics Engeering Student however I have developed experience in a variety of other disciplines. My best skill is how quickly I learn. Check my experience for everything I've worked with.
user_title: Robotics Engineer
email: padamadan.adrian@gmail.com
github_username:  adrpad

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
